services:
  django:
    container_name: nubocore_service
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    volumes:
      - ./service:/app
    depends_on:
      - db
    env_file: '.env'
    restart: always

  db:
    env_file: '.env'
    container_name: nubocore_db
    image: postgres:17
    environment:
      POSTGRES_DB: nubocore_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  docs:
    build:
      context: .
      dockerfile: docs/Mkdocsfile
    container_name: nubocore_docs
    ports:
      - "8009:8009"
    volumes:
      - .:/app
    working_dir: /app
    command: mkdocs serve --dev-addr=0.0.0.0:8009 --dirtyreload --watch /docs
    restart: always

volumes:
  postgres_data: